import Providers from "@/components/Providers";
import Ifooter from "@/components/footer/footer";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import type { Metadata } from 'next';
import dynamic from "next/dynamic";
import { Inter } from 'next/font/google';
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "<Le/Tuan>",
  description: "Generated by LPAT",
}

interface Props {
  children: React.ReactNode;
}
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout(props: Props) {
  const Header = dynamic(() => import("@/components/AppBar"), { ssr: true });
  return (
    <html lang="en">
      <body className={cn(inter.className,
        "bg-fixed  max-w-full min-h-screen "
      )}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <div className={cn(
              "lg:px-[20px]",
              "md:px-[5px]",
              "sm:px-[0px]",
            )}>
              {props.children}
            </div>
            <Toaster />
            <Ifooter />
          </ThemeProvider>
        </Providers>
      </body>

    </html>
  );
}
